instawork_assignment/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('teamManagement.urls'))
]

teamManagement/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from teamManagement import views

app_name = 'teamManagement'

urlpatterns = [
    path('', csrf_exempt(views.LoginView.as_view()), name='login'),
    path('register', csrf_exempt(views.RegisterView.as_view()), name='register'),
    path('list', views.TeamListView.as_view(), name='team_list'),
    path('add', views.TeamAddView.as_view(), name='add_member'),
    path('edit/<int:member_id>', views.TeamEditView.as_view(), name='edit_member'),
    path('delete/<int:pk>', views.TeamDeleteView.as_view(), name='delete_member'),
    path('logout', csrf_exempt(views.user_logout), name='logout')
]

teamManagement/models.py
# models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager, PermissionsMixin
from django.db import models


# Custom manager for TeamMember model
class TeamMemberManager(BaseUserManager):
    # Create a regular TeamMember
    def create_team_member(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        team_member = self.model(email=email, **extra_fields)
        team_member.set_password(password)
        team_member.save(using=self._db)
        return team_member

    # Create a superuser with admin role
    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('role', 'admin')

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_team_member(email, password, **extra_fields)


# Custom TeamMember model inheriting from AbstractUser and PermissionsMixin
class TeamMember(AbstractUser, PermissionsMixin):
    # Choices for the 'role' field
    ROLE_CHOICES = [
        ('regular', "Regular"),
        ('admin', "Admin"),
    ]

    # Fields for the TeamMember model
    email = models.EmailField(unique=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    role = models.CharField(max_length=50, choices=ROLE_CHOICES, default='regular')
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=True)

    # Custom manager for the TeamMember model
    objects = TeamMemberManager()

    # String representation of the TeamMember
    def __str__(self):
        return self.first_name

    # Custom save method to set the username as the email
    def save(self, *args, **kwargs):
        self.username = self.email
        super().save(*args, **kwargs)

teamManagement/forms.py
# teams/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.core.exceptions import ValidationError
from django.forms import RadioSelect

from .models import TeamMember


# Form for adding/editing Team Members
class TeamMemberForm(forms.ModelForm):
    class Meta:
        model = TeamMember
        fields = ['first_name', 'last_name', 'email', 'phone_number', 'role']

        # Explicitly set the widget for the 'role' field to RadioSelect
        widgets = {
            'role': RadioSelect()
        }


# Form for user registration, extends Django's UserCreationForm
class RegistrationForm(UserCreationForm):
    # Additional fields for first name and last name
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)

    class Meta:
        model = TeamMember
        fields = ['first_name', 'last_name', 'email', 'phone_number', 'password1', 'password2']

    # Custom validation for the email field to check for uniqueness
    def clean_email(self):
        email = self.cleaned_data['email']
        existing_user = TeamMember.objects.filter(email=email).exclude(pk=self.instance.pk).first()
        if existing_user:
            raise ValidationError("This email is already in use.")
        return email

    # Custom save method to set the default role to 'regular'
    def save(self, commit=True):
        user = super().save(commit=False)
        user.role = 'regular'
        if commit:
            user.save()
        return user


# Form for user login, extends Django's AuthenticationForm
class LoginForm(AuthenticationForm):
    class Meta:
        model = TeamMember
        fields = ['username', 'password']

teamManagement/views.py
# Import necessary modules and classes from Django
from django.contrib.auth import authenticate, login, logout
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, FormView

# Import custom forms and models from the application
from .forms import TeamMemberForm, RegistrationForm, LoginForm
from .models import TeamMember

# Define your views below


# Team members List View
class TeamListView(ListView):
    model = TeamMember
    template_name = 'teamManagement/team_list.html'
    context_object_name = 'team_members'


# Team member Add view
class TeamAddView(CreateView):
    model = TeamMember
    form_class = TeamMemberForm
    template_name = 'teamManagement/add_edit_member.html'
    success_url = '/list'

    def form_valid(self, form):
        # Access the logged-in user
        user = self.request.user

        # Access the selected role from the form
        selected_role = form.cleaned_data.get('role')

        # Check if the user is an admin
        if not user.role == 'admin' and selected_role == 'admin':
            form.add_error('role', 'Regular users can only select the "regular" role.')
            return self.form_invalid(form)
        # Continue with the default behavior of the parent class
        return super().form_valid(form)


# Team Member Edit View
class TeamEditView(UpdateView):
    model = TeamMember
    form_class = TeamMemberForm
    template_name = 'teamManagement/add_edit_member.html'
    success_url = '/list'

    def get_object(self, queryset=None):
        return get_object_or_404(TeamMember, id=self.kwargs['member_id'])


# Team Member Delete View
class TeamDeleteView(DeleteView):
    model = TeamMember
    template_name = 'teamManagement/add_edit_member.html'  # Create a delete confirmation template
    success_url = '/list'


# Register Team Member/User View
class RegisterView(SuccessMessageMixin, FormView):
    template_name = 'teamManagement/register.html'
    form_class = RegistrationForm
    success_url = 'list'  # Redirect to the list page after successful registration
    success_message = "Registration successful. You are now logged in."

    def form_valid(self, form):
        # Save the form data and log in the user
        user = form.save()
        login(self.request, user)
        return super().form_valid(form)


# Login Team Member/User View
class LoginView(FormView):
    template_name = 'teamManagement/login.html'
    form_class = LoginForm
    success_url = 'list'  # Redirect to home page after successful login

    def form_valid(self, form):
        user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
        if user:
            login(self.request, user)
        return super().form_valid(form)


# Logout view
def user_logout(request):
    logout(request)
    return redirect('/')

templates/teamManagement/add_edit_member.html
<!-- edit_member.html -->
{% extends 'teamManagement/base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}">
{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        <div class="hero">
            <div class="title">{% if 'edit' in request.path %}Edit {% else %} Add a{% endif %} Team Member</div>
            <div class="subtitle">
                {% if 'edit' in request.path %}
                    Edit contact info and role.
                {% else %}
                    Set email, location, and role.
                {% endif %}
            </div>
            <p>Info</p>
            {#  I have not added action because in this case same view will be called when save button is clicked#}
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.first_name.id_for_label }}">First Name:</label>
                    {{ form.first_name }}
                </div>

                <div class="form-group">
                    <label for="{{ form.first_name.id_for_label }}">Last Name:</label>
                    {{ form.last_name }}
                </div>

                <div class="form-group">
                    <label for="{{ form.first_name.id_for_label }}">Email:</label>
                    {{ form.email }}
                </div>

                <div class="form-group">
                    <label for="{{ form.phone_number.id_for_label }}">Phone Number:</label>
                    {{ form.phone_number }}
                </div>

                <div class="form-group">
                    <label for="{{ form.role.id_for_label }}">Role:</label>
                    {{ form.role }}
                    {{ form.errors.role }}
                </div>
                <button type="submit">Save</button>
            </form>

            {% if 'edit' in request.path %}
                <form method="post" action="{% url 'teamManagement:delete_member' pk=object.pk %}">
                    {% csrf_token %}
                    <button type="submit">Delete</button>
                </form>
            {% endif %}
        </div>
    {% else %}
        <div>
            Please
            <a href="{% url 'teamManagement:login' %}">Log In .</a>
        </div>
    {% endif %}
{% endblock %}

templates/teamManagement/base.html
<!-- base.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Team Management{% endblock %}</title>
    <!-- Add your CSS and other head elements here -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    {% block css %}
    {% endblock %}
</head>
<body>
<div id="content" class="centerDiv">
    {% block content %}{% endblock %}
</div>

<!-- Add your JavaScript and other body elements here -->

</body>
</html>

templates/teamManagement/login.html
{% extends 'teamManagement/base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
{% endblock %}
{% block content %}
    <div class="form-container">
        <h3 style="text-align: center; padding-top: 10px;">Login</h3>
        <form class="login-form" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form.username.id_for_label }}">Email:</label>
                {{ form.username }}
            </div>

            <div class="form-group">
                <label for="{{ form.password.id_for_label }}">Password:</label>
                {{ form.password }}
            </div>

            {% if form.errors %}
                {{ form.non_field_errors }}
            {% endif %}
            {% if next %}
                {% if user.is_authenticated %}
                    <p>Your account doesn't have access to this page. To proceed,
                        please login with an account that has access.</p>
                {% else %}
                    <p>Please login to see this page.</p>
                {% endif %}
            {% endif %}

            <button type="submit" class="btn btn-primary button">Login</button>
            <input type="hidden" name="next" value="{{ next }}">
        </form>
        <p class="register-link">Don't have an account? <a href="{% url 'teamManagement:register' %}">Register</a></p>
    </div>
{% endblock %}

templates/teamManagement/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome to Team Management!</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/register.css' %}">
</head>
<body>
<div class="form-container-parent">
    <div class="form-container">
        <h3 style="text-align: center; padding-top: 10px;">Sign Up</h3>
        <form class="register-form" method="post" enctype="multipart/form-data">
            {{ form.non_field_errors | safe }}
            <div class="form-group">
                <label for="{{ form.email.id_for_label }}">Email:</label>
                {{ form.email }}
                {{ form.email.errors | safe }}
            </div>
            <div class="form-group">
                <label for="{{ form.first_name.id_for_label }}">First name:</label>
                {{ form.first_name }}
                {{ form.first_name.errors | safe }}
            </div>
            <div class="form-group">
                <label for="{{ form.last_name.id_for_label }}">Last name:</label>
                {{ form.last_name }}
                {{ form.last_name.errors | safe }}
            </div>
            <div class="form-group">
                <label for="{{ form.password1.id_for_label }}">Password:</label>
                {{ form.password1 }}
                {{ form.password1.errors | safe }}
            </div>
            <div class="form-group">
                <label for="{{ form.password2.id_for_label }}">Confirm Password:</label>
                {{ form.password2 }}
                {{ form.password2.errors | safe }}
            </div>
            <br>
            <div class="flex-container">
                <button type="submit" class="btn btn-primary button">Signup</button>
            </div>
        </form>
        <p class="login-link">Already have an account? <a href="{% url 'teamManagement:login' %}">Login</a></p>
    </div>
</div>
</body>

templates/teamManagement/team_list.html
{% extends 'teamManagement/base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/team_list.css' %}">
{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        {% if user.role == 'admin' %}
            <p>Welcome, Admin!</p>
        {% else %}
            <p>You are a regular user.</p>
        {% endif %}
        <div class="hero">
            <div class="title">
                <div>
                    Team members
                </div>
                <div><a class="add" href="{% url 'teamManagement:add_member' %}">+</a></div>
            </div>
            <div class="subtitle">You have {{ team_members.count }} team members</div>

            <div class="list_div">
                {% for team_member in team_members %}
                    <div class="line"></div>
                    {% if user.role == 'admin' or user.role == 'regular' and team_member.role == 'regular' %}
                        <a class="text" href="{% url 'teamManagement:edit_member' team_member.id %}">
                            {{ team_member.first_name }} {{ team_member.last_name }}
                            - {{ team_member.get_role_display }}
                            <p>{{ team_member.phone_number }}</p>
                            <p>{{ team_member.email }}</p>
                        </a>
                    {% else %}
                        <div>
                            {{ team_member.first_name }} {{ team_member.last_name }}
                            - {{ team_member.get_role_display }}
                            <p>{{ team_member.phone_number }}</p>
                            <p>{{ team_member.email }}</p>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
            <div class="line"></div>

            {% if user.role == 'admin' or user.role == 'regular' and team_member.role == 'regular' %}
            {% else %}
                <div>You cannot edit admin users</div>
            {% endif %}

            <!-- Add more content or customize based on your needs -->
        </div>
    {% else %}
        <div>
            Please
            <a href="{% url 'teamManagement:login' %}">Log In .</a>
        </div>
    {% endif %}
{% endblock %}

templates/teamManangement/base.html
<!-- base.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Team Management{% endblock %}</title>
    <!-- Add your CSS and other head elements here -->
</head>
<body>


<div id="content">
    {% block content %}{% endblock %}
</div>

<!-- Add your JavaScript and other body elements here -->

</body>
</html>